name: Windows Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_windows:
    name: Build Windows Binaries
    runs-on:
      windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Dependencies
        uses: ilammy/msvc-dev-cmd@v1
        
      - name: Create Project
        working-directory: mp/src
        run: devtools/bin/vpc.exe /2013 /ff +game /mksln Game_FF.sln

      - name: Build Project
        working-directory: mp/src
        run: devenv Game_FF.sln /Build Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ff_windows
          path: |
            game/FortressForever2013/bin/*.dll
            game/FortressForever2013/bin/*.pdb
          retention-days: 1